/// Flutter icons CarIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CarIcons
///      fonts:
///       - asset: fonts/CarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CarIcons {
  CarIcons._();

  static const _kFontFam = 'CarIcons';

  static const IconData taxi = IconData(0xe801, fontFamily: _kFontFam);
}
