/// Flutter icons Cart
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Cart
///      fonts:
///       - asset: fonts/Cart.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Cart {
  Cart._();

  static const _kFontFam = 'Cart';

  static const IconData shopping_cart_of_horizontal_lines_design = const IconData(0xe800, fontFamily: _kFontFam);
}